# Generated by Django 2.2.6 on 2022-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_unica', models.CharField(max_length=500)),
                ('no_reg', models.IntegerField()),
                ('clave', models.CharField(blank=True, max_length=500, null=True)),
                ('cve_epoca', models.CharField(max_length=500)),
                ('rubro', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('referencia', models.TextField(blank=True, max_length=500, null=True)),
                ('sala_pleno', models.CharField(blank=True, max_length=500, null=True)),
                ('IDSCJN', models.IntegerField()),
                ('IDSCJN1', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Administrador Sentencias',
                'verbose_name_plural': 'Administrador Sentencias',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_unica', models.CharField(blank=True, max_length=500, null=True)),
                ('no_reg', models.IntegerField()),
                ('materia', models.TextField(blank=True, null=True)),
                ('cve_tesis', models.CharField(max_length=500)),
                ('cve_epoca', models.CharField(max_length=500)),
                ('rubro', models.TextField()),
                ('texto', models.TextField()),
                ('precedente', models.TextField()),
                ('referencia', models.TextField()),
                ('sala_pleno', models.CharField(max_length=500)),
                ('estado', models.IntegerField()),
                ('acuerdo', models.CharField(blank=True, max_length=500, null=True)),
                ('IUS', models.IntegerField()),
                ('IUS1', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'tesis'), (2, 'jurisprudencia')], default=1)),
            ],
            options={
                'verbose_name': 'Administrador Tesis',
                'verbose_name_plural': 'Administrador Tesis',
                'ordering': ['cve_tesis'],
            },
        ),
    ]
