# Generated by Django 2.2.6 on 2022-03-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='IUS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='IUS1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
