# Generated by Django 2.2.6 on 2022-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0002_auto_20220322_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN1',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='no_reg',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='no_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
