# Generated by Django 2.2.6 on 2022-04-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0003_auto_20220405_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='no_reg',
            field=models.IntegerField(),
        ),
    ]
