# Generated by Django 2.2.6 on 2022-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0004_auto_20220405_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='cve_epoca',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='cve_tesis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
