# Generated by Django 2.2.6 on 2022-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0005_auto_20220405_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='precedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='referencia',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='rubro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='texto',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
