# Generated by Django 2.2.6 on 2022-09-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0007_auto_20220405_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='IDSCJN1',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sentencia',
            name='no_reg',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='IUS',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='IUS1',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='cve_epoca',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='cve_tesis',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='estado',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='no_reg',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='precedente',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='referencia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='rubro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='sala_pleno',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='status',
            field=models.IntegerField(choices=[(1, 'tesis'), (2, 'jurisprudencia'), (3, 'jurisprudencia-suspendida'), (4, 'modificadas'), (5, 'excepciones')], default=1),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
