# Generated by Django 2.2.6 on 2022-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0009_auto_20220908_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='nota',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
