# Generated by Django 2.2.6 on 2022-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stj', '0010_auto_20220908_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='estado',
            field=models.IntegerField(blank=True),
        ),
    ]
